version: '3'
services:
    database:
      image: 'postgres:alpine'
      ports:
          -   5438:5432
      environment:
        POSTGRES_USER: crazy88
        POSTGRES_PASSWORD: '@password12'
        POSTGRES_DB: permissions_db

    permissions_api:
      image: 'permissions_app_api'

      env_file:
          -   .env
      ports:
          -   8500:8500
      depends_on:
          -   database
      restart: always