version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASEa_URL: postgres://myuser:mypassword@db:5432/myappdb

volumes:
  db_data:
